### ISSUE TITLE
Pipeline requires more libraries

### ISSUE THREAD

**Issue by JohnChrys** [dipetkov/eems#22]
Hello,
I am using EEMS in a server where I don't have sudo priviledges and it turns out EEMS needs more libraries than you say in the readme. 
When I tried running it it also couldn't find fiona, collections, mpl_toolkit and descartes along with pandas and shapely.
Could you add those to the list of needed packages?

**Comment by BenjaminPeter** [comment]
hi John,

these are dependencies on some python stuff I pushed to the repo to make
stuff a bit easier, but they are not needed to run eems (and probably not
functional). Just use the bed2diffs and runeems executables directly.
Desi, you probably should delete the pipeline folder as it is not used.

- Ben

**Comment by JohnChrys** [comment]
Hi Mr Peter,
Thank you for your reply. Even though they're not needed to run it, when I do 
python pipeline_cli.py -h 
upon not detecting those packages on the server it fails and outputs an error message. I haven't tried running the pipeline per se, but I imagine failing to load these libraries would cause the run to fail as it does for the -h command.

I am now trying to use the bed2diffs and runeems executables, yes. If they're the only ones worth running right now, you could always make a vignette for them and/or the best way of running them that works for you.

John

**Comment by meisei4** [comment]
Is there any plans for this pipeline to be updated to work with modern package versions?
