### ISSUE TITLE
Error: Check that the genotype matrix is a ..

### ISSUE THREAD

**Issue by tommydevitt** [dipetkov/eems#35]
Hi, trying to use runeems_sats and am getting "Error: Check that the genotype matrix is a nIndiv x 128 matrix. I'm confused by this. Shouldn't the matrix be nIndiv x nLoci (=n x 2L for L diploid loci)? Pasted below is the output: 

Tom-Devitts-MBP:src tom$ ./runeems_sats --params params-chain1.ini
Using Boost 1_61 (EEMS was tested with version 1_57)
      Eigen 3.2.9 (EEMS was tested with version 3.2.2)

  Will save EEMS output to ../data/gopher_eems_200demes_chain1/
[Habitat::initialize]
  Loaded habitat points from ../data/gopher_eems.outer
  Input habitat: 
    POLYGON((30.9264 -87.7875,30.7943 -87.7436,30.6999 -87.6777,30.5108 -87.6777,30.3592 -87.6777,30.2454 -87.5019,30.2264 -87.3261,30.2644 -87.1283,30.3023 -86.9306,30.3023 -86.7768,30.3023 -86.5351,30.3023 -86.2494,30.1695 -86.0077,29.9603 -85.832,29.7125 -85.6342,29.5979 -85.3925,29.5979 -85.0849,29.617 -84.997,29.6552 -84.8652,29.7125 -84.5356,29.7888 -84.4477,29.8269 -84.2939,29.8841 -84.206,29.9222 -84.0302,29.8841 -83.9423,29.846 -83.8984,29.8079 -83.8324,29.7316 -83.7445,29.5979 -83.6127,29.5023 -83.5468,29.4067 -83.4369,29.2918 -83.3271,29.2343 -83.2172,29.1767 -83.1293,29.0616 -83.0195,29.0039 -82.9096,28.8886 -82.8437,28.7731 -82.8437,28.6767 -82.8876,28.5417 -82.8876,28.4258 -82.9316,28.3291 -82.9535,28.2711 -82.9535,28.1356 -82.9535,27.9998 -82.9755,27.9222 -82.9755,27.8639 -82.9755,27.6695 -82.9755,27.5722 -82.8656,27.4748 -82.8656,27.4163 -82.8437,27.221 -82.7558,27.0842 -82.602,26.8492 -82.4482,26.7315 -82.3603,26.5744 -82.2944,26.4564 -82.2284,26.4367 -82.1845,26.3974 -82.0966,26.358 -82.0966,26.2595 -82.0087,26.2201 -81.9867,26.0623 -81.8988,25.9636 -81.8769,25.8845 -81.7231,25.7659 -81.6352,25.6471 -81.5033,25.4091 -81.3495,25.2105 -81.3495,25.0514 -81.3495,24.9717 -81.2177,24.9717 -81.0859,24.892 -80.7782,24.9717 -80.4706,25.0912 -80.1191,25.4091 -80.0751,25.6867 -79.9872,26.0426 -79.9433,26.4367 -79.8993,26.7511 -79.8993,27.2992 -79.8993,27.5332 -79.8993,27.9222 -80.163,28.1162 -80.2509,28.2711 -80.3827,28.5031 -80.2948,28.696 -80.2948,29.2726 -80.7343,29.5406 -80.998,29.7697 -80.998,30.1505 -81.0419,30.3403 -81.0419,30.3687 -81.1078,30.5013 -81.1957,30.6148 -81.2946,30.7188 -81.3166,30.8038 -81.4814,30.8226 -81.7011,30.8792 -81.8,30.8792 -81.9318,30.8792 -82.0307,30.8226 -82.0966,30.7188 -82.1076,30.6054 -82.1076,30.6621 -82.3053,30.6621 -82.4591,30.6905 -82.6899,30.6905 -82.8986,30.6999 -83.2611,30.7188 -83.6347,30.7566 -84.0082,30.7754 -84.4147,30.8038 -84.7443,30.9264 -84.8432,31.0206 -84.8652,31.0582 -84.953,31.077 -85.1508,31.0958 -85.5463,31.0958 -85.8759,31.1147 -86.2934,31.1711 -86.7548,31.1335 -87.3261,31.1147 -87.5898,31.077 -87.6996,31.0206 -87.7216,30.9829 -87.7216,30.9264 -87.7436,30.9264 -87.7875))
[Habitat::initialize] Done.

[Graph::initialize]
  Generate population grid and sample assignment
  Loaded sample coordinates from ../data/gopher_eems.coord
  There are 31 observed demes (out of 184 demes)
  The population grid has 184 demes and 470 edges
  There are 1191 samples assigned to 31 observed demes
[Graph::initialize] Done.

[Diffs::initialize]
Error: Check that the genotype matrix is a nIndiv-by-128 matrix.

**Comment by dipetkov** [comment]
Yes, it should. Can you check that in the input param file `nSites = L` is set to whatever the number of loci `L` is?

**Comment by tommydevitt** [comment]
Yep, that was it. Thanks.
