### ISSUE TITLE
Error: Check that the dissimilarity matrix is a square nIndiv-by-nIndiv matrix.

### ISSUE THREAD

**Issue by csmikles** [dipetkov/eems#36]
I am receiving this error message in the nDemes log file when trying to run EEMS, in the [Diffs::initialize] section. 

"Error: Check that the dissimilarity matrix is a square nIndiv-by-nIndiv matrix."

I checked that the dissimilarity matrix (named datapath.diffs) is in fact a square, and checked that the end-of-line characters are in unix. The original structure file does have missing data (0s), but I do not think that should be a problem. There are no issues with the .outer and .coord files, and the program successfully initialized and completed the habitat and graph runs. 

Thanks.

**Comment by nitinra** [comment]
I am facing the same problem. is there a solution for this?

**Comment by hanjizhe18** [comment]
Hello, I am experiencing the same problem, is there any solution? Is it caused by too many missing bits of data in the vcf file?
![Uploading 1710813458688.jpg…]()

**Comment by tobitliyandja** [comment]
Did anyone resolved this problem?
