### ISSUE TITLE
Question about adding geographic map

### ISSUE THREAD

**Issue by guojingfang123** [dipetkov/eems#45]
Hi Desislava,
thank you very much for your detailed introduction of EEMS. I have a question about adding geographic map. I can add borders to countries. Can boundaries be added within countries?For example, add the provinces of China.
Looking forward to your reply.
Best,
Hanna

**Comment by dipetkov** [comment]
Yes. There is an example how to that in the documentation. Look up the documentation with `?eems.plots`. The relevant example is this one -- it adds a map of Africa explicitly.
```
# Apply the Mercator projection and add the map of Africa
# Don't forget to apply the same projection to the map as well
map_world <- getMap()
map_africa <- map_world[which(map_world@data$continent == "Africa"), ]
map_africa <- spTransform(map_africa, CRS(projection_mercator))
eems.plots(
  mcmcpath = eems_results,
  plotpath = paste0(name_figures, "-shapefile-projected"),
  longlat = TRUE,
  projection.in = projection_none,
  projection.out = projection_mercator,
  m.plot.xy = {
    plot(map_africa, col = NA, add = TRUE)
  },
  q.plot.xy = {
    plot(map_africa, col = NA, add = TRUE)
  }
)
```
