### ISSUE TITLE
shiny app error

### ISSUE THREAD

**Issue by PattSS** [dipetkov/eems#51]
Hello,

I am trying to use the shiny app. I uploaded the .RData file , however I got this error: An error has occurred. Check your logs or contact the app author for clarification.
I have no extra information about what is possibly wrong, I don't know if I am doing something wrong or if the app is not available at the moment? Any idea? Thank you!

**Comment by dipetkov** [comment]
What shiny app are you referring to?

**Comment by dipetkov** [comment]
The shiny app was just a little experiment. I'm not surprised it's not working since I haven't updated it since then.
