### ISSUE TITLE
How about treat individuals from one location as a population?

### ISSUE THREAD

**Issue by willright28** [dipetkov/eems#54]
Hi all
According to eems's manual this software is a individual-based approach to simulate the genetic dissimlarity between pairs, but if we access samples from the same geographical location to a **population** and simulate difference between those **population**, will it influence the result? For example, if I got 100 samples from 10 locations, then I will calculate a pop's genetic dissimlarity matrix with dim 10 by using other software, and run eems by setting **nIndiv** to 10. 
I'm totally awaring of how bad this question is, however I have to have a try for some terrible reasons.
And what's more terrible is that eems gave error information 'matrix is not a full-rank matrix' when I implemented it, but I can not find why..
I really appreciate it if someone could convince me it's a stupid idea to do that! Thanks in advanced!

BEST

**Comment by dipetkov** [comment]
With individual-level data we get to see how dissimilar individuals in the same deme/location are to each other compared to individuals in other demes. With population-level data we don't have information about dissimilarities within demes.

And the "full-rank distance matrix" check makes sure the matrix of genetic dissimilarities is a proper distance matrix. (Otherwise the math doesn't work out.)

**Comment by dipetkov** [comment]
Your question reminded me of a previous question about using the matrix of F_{ST}s as input.
You can read more about this in the folder "Pairwise_FSTs".

**Comment by willright28** [comment]
Thanks for your reply，I will check the folder



---Original---
From: "Desislava ***@***.***&gt;
Date: Sun, Aug 8, 2021 08:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dipetkov/eems] How about treat individuals from one location as a population? (#54)




 
Your question reminded me of a previous question about using the matrix of F_{ST}s as input.
 You can read more about this in the folder "Pairwise_FSTs".
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
