### ISSUE TITLE
How to extract value based on coordinate

### ISSUE THREAD

**Issue by willright28** [dipetkov/eems#64]
Hi all,

Does anyone know how to extract the value of the effective migration rate based on coordinates? Or to produce raster files from the plot function.

Thanks in advance!

**Comment by otterhans** [comment]
Hello, have you solved the problem? I have the same question: Is there any function to create a raster (.tif) map, not a .png, in order to work with GIS?

**Comment by willright28** [comment]
Hi @otterhans ,

The eems.plots function will save xyz files (migrant and diversity rates) as an .Rdata in the direction you save the pdf/png, so just load the Rdata into R environment and you can use function like rasterFromXYZ to create a raster object.

Best
